# Generated by Django 3.0.7 on 2020-06-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_usersanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='questions_count',
        ),
    ]
