# Generated by Django 3.0.7 on 2020-06-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_remove_quiz_questions_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.ImageField(default='blog/images/already.png', upload_to=''),
        ),
    ]
