# Generated by Django 3.0.7 on 2020-06-10 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_quiz_questions_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='questions_count',
        ),
    ]
